# Generated by Django 2.0.5 on 2018-05-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180517_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='author',
            field=models.IntegerField(default=1),
        ),
    ]
