# Generated by Django 2.0.5 on 2018-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180527_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=11)),
                ('end', models.CharField(max_length=11)),
            ],
        ),
    ]
