# Generated by Django 2.0.5 on 2018-05-31 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180530_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
    ]
