# Generated by Django 2.0.5 on 2018-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180601_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hexColor',
            field=models.CharField(default='007700', max_length=10),
            preserve_default=False,
        ),
    ]
