# Generated by Django 2.0.5 on 2018-06-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_event_hexcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hexColor',
        ),
    ]
