# Generated by Django 2.0.5 on 2018-06-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_event_hexcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hexColor',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
